import type { AssortmentAnalysisSource } from "./assortment-curation-content";

/** Design-spec analysis dataset (1032 SKUs, StyleCurrent / Summit Trail / CityLine). */
export const ASSORTMENT_ANALYSIS_DEMO: AssortmentAnalysisSource = {
  id: "seller-excel",
  label: "Excel shared by seller",
  type: "seller_submission",
  analysis: {
    totalSkus: 1032,
    wercsFlagged: 0,
    homeSkus: 715,
    apparelSkus: 317,
    uniqueBrands: 3,
    protectedBrands: 1,
    barcodesAvailable: 672,
    barcodesInvalid: 220,
    barcodesUnavailable: 50,
  },
  brands: [
    { brand: "StyleCurrent", skus: 345, protected: true, agp: 0 },
    { brand: "SummitTrail", skus: 276, protected: false, agp: 0 },
    { brand: "CityLine", skus: 465, protected: false, agp: 0 },
  ],
  itemTypes: [
    {
      itemType: "Speaker",
      totalSkus: 142,
      coveragePercent: 52,
      barcodeAvailable: 120,
      barcodeInvalid: 15,
      barcodeUnavailable: 7,
    },
    {
      itemType: "Athletic Shoes",
      totalSkus: 98,
      coveragePercent: 48,
      barcodeAvailable: 85,
      barcodeInvalid: 8,
      barcodeUnavailable: 5,
    },
    {
      itemType: "Kitchen Appliance",
      totalSkus: 110,
      coveragePercent: 61,
      barcodeAvailable: 95,
      barcodeInvalid: 10,
      barcodeUnavailable: 5,
    },
    {
      itemType: "Midi Dress",
      totalSkus: 85,
      coveragePercent: 44,
      barcodeAvailable: 72,
      barcodeInvalid: 9,
      barcodeUnavailable: 4,
    },
    {
      itemType: "Table Lamp",
      totalSkus: 76,
      coveragePercent: 38,
      barcodeAvailable: 58,
      barcodeInvalid: 12,
      barcodeUnavailable: 6,
    },
    {
      itemType: "Throw Pillow",
      totalSkus: 64,
      coveragePercent: 55,
      barcodeAvailable: 52,
      barcodeInvalid: 8,
      barcodeUnavailable: 4,
    },
    {
      itemType: "Wall Art",
      totalSkus: 58,
      coveragePercent: 41,
      barcodeAvailable: 44,
      barcodeInvalid: 10,
      barcodeUnavailable: 4,
    },
    {
      itemType: "Area Rug",
      totalSkus: 52,
      coveragePercent: 36,
      barcodeAvailable: 38,
      barcodeInvalid: 9,
      barcodeUnavailable: 5,
    },
  ],
  skuDrillDown: [
    {
      partnerSku: "000001",
      barcode: "0194251000001",
      brand: "StyleCurrent",
      productTitle: "StyleCurrent Floral Midi Dress Navy",
      productDescription: "Floral print midi dress with short sleeves.",
      partnerItemCategory: "Apparel",
      partnerItemSubcategory: "Dresses",
      shipSpeed: "2 days",
      retailPrice: "$49.99",
      primaryImageUrl: "https://cdn.example.com/stylecurrent/midi-navy.jpg",
      bu: "Apparel and Accessories",
      division: "Women's Apparel",
      department: "Dresses",
      itemType: "Midi Dress",
      protectedBrand: true,
      barcodeStatus: "Available",
      wercsStatus: "UPC is not currently registered",
      wercsActionRequired: "Reach out to Supplier to ensure registration",
    },
    {
      partnerSku: "000002",
      barcode: "0194251000002",
      brand: "StyleCurrent",
      productTitle: "StyleCurrent Linen Blend Shirt White",
      productDescription: "Relaxed fit linen blend button-down shirt.",
      partnerItemCategory: "Apparel",
      partnerItemSubcategory: "Tops",
      shipSpeed: "2 days",
      retailPrice: "$39.99",
      primaryImageUrl: "https://cdn.example.com/stylecurrent/shirt-white.jpg",
      bu: "Apparel and Accessories",
      division: "Women's Apparel",
      department: "Tops",
      itemType: "Shirt",
      protectedBrand: true,
      barcodeStatus: "Available",
      wercsStatus: "Registered",
      wercsActionRequired: "—",
    },
    {
      partnerSku: "000003",
      barcode: "0194251000003",
      brand: "Summit Trail",
      productTitle: "Summit Trail Hiking Boot Waterproof",
      productDescription: "Waterproof leather hiking boot with Vibram sole.",
      partnerItemCategory: "Footwear",
      partnerItemSubcategory: "Boots",
      shipSpeed: "3 days",
      retailPrice: "$129.99",
      primaryImageUrl: "https://cdn.example.com/summit/boot-waterproof.jpg",
      bu: "Apparel and Accessories",
      division: "Men's Apparel",
      department: "Footwear",
      itemType: "Athletic Shoes",
      protectedBrand: true,
      barcodeStatus: "Available",
      wercsStatus: "Registered",
      wercsActionRequired: "—",
    },
    {
      partnerSku: "000004",
      barcode: "0194251000004",
      brand: "CityLine",
      productTitle: "CityLine Bluetooth Speaker Mini",
      productDescription: "Portable Bluetooth speaker with 12hr battery.",
      partnerItemCategory: "Electronics",
      partnerItemSubcategory: "Audio",
      shipSpeed: "1 day",
      retailPrice: "$34.99",
      primaryImageUrl: "https://cdn.example.com/cityline/speaker-mini.jpg",
      bu: "Home",
      division: "Electronics",
      department: "Audio",
      itemType: "Speaker",
      protectedBrand: false,
      barcodeStatus: "Unavailable",
      wercsStatus: "Pending supplier documentation",
      wercsActionRequired: "Request WERCS documentation from supplier",
    },
    {
      partnerSku: "000005",
      barcode: "0194251000005",
      brand: "CityLine",
      productTitle: "CityLine Air Fryer 4.2 Qt",
      productDescription: "Digital air fryer with preset cooking modes.",
      partnerItemCategory: "Kitchen & Dining",
      partnerItemSubcategory: "Small Appliances",
      shipSpeed: "2 days",
      retailPrice: "$79.99",
      primaryImageUrl: "https://cdn.example.com/cityline/air-fryer.jpg",
      bu: "Home",
      division: "Kitchen",
      department: "Appliances",
      itemType: "Kitchen Appliance",
      protectedBrand: false,
      barcodeStatus: "Invalid",
      wercsStatus: "Barcode format invalid",
      wercsActionRequired: "Verify barcode with supplier",
    },
    {
      partnerSku: "000006",
      barcode: "0194251000006",
      brand: "StyleCurrent",
      productTitle: "StyleCurrent Wide Leg Pant Black",
      productDescription: "High-rise wide leg pant in stretch twill.",
      partnerItemCategory: "Apparel",
      partnerItemSubcategory: "Pants",
      shipSpeed: "2 days",
      retailPrice: "$54.99",
      primaryImageUrl: "https://cdn.example.com/stylecurrent/wide-leg-black.jpg",
      bu: "Apparel and Accessories",
      division: "Women's Apparel",
      department: "Bottoms",
      itemType: "Pants",
      protectedBrand: true,
      barcodeStatus: "Available",
      wercsStatus: "Registered",
      wercsActionRequired: "—",
    },
    {
      partnerSku: "000007",
      barcode: "0194251000007",
      brand: "Summit Trail",
      productTitle: "Summit Trail Trail Running Shoe",
      productDescription: "Lightweight trail runner with aggressive tread.",
      partnerItemCategory: "Footwear",
      partnerItemSubcategory: "Athletic",
      shipSpeed: "2 days",
      retailPrice: "$89.99",
      primaryImageUrl: "https://cdn.example.com/summit/trail-runner.jpg",
      bu: "Apparel and Accessories",
      division: "Men's Apparel",
      department: "Footwear",
      itemType: "Athletic Shoes",
      protectedBrand: false,
      barcodeStatus: "Available",
      wercsStatus: "Registered",
      wercsActionRequired: "—",
    },
    {
      partnerSku: "000008",
      barcode: "0194251000008",
      brand: "CityLine",
      productTitle: "CityLine Ceramic Table Lamp",
      productDescription: "Modern ceramic base table lamp with linen shade.",
      partnerItemCategory: "Home Decor",
      partnerItemSubcategory: "Lighting",
      shipSpeed: "3 days",
      retailPrice: "$64.99",
      primaryImageUrl: "https://cdn.example.com/cityline/table-lamp.jpg",
      bu: "Home",
      division: "Decor",
      department: "Lighting",
      itemType: "Table Lamp",
      protectedBrand: false,
      barcodeStatus: "Unavailable",
      wercsStatus: "Not submitted",
      wercsActionRequired: "Reach out to Supplier to ensure registration",
    },
    {
      partnerSku: "000009",
      barcode: "0194251000009",
      brand: "StyleCurrent",
      productTitle: "StyleCurrent Knit Sweater Heather Gray",
      productDescription: "Crew neck sweater in soft cotton blend.",
      partnerItemCategory: "Apparel",
      partnerItemSubcategory: "Sweaters",
      shipSpeed: "2 days",
      retailPrice: "$44.99",
      primaryImageUrl: "https://cdn.example.com/stylecurrent/sweater-gray.jpg",
      bu: "Apparel and Accessories",
      division: "Women's Apparel",
      department: "Tops",
      itemType: "Sweater",
      protectedBrand: true,
      barcodeStatus: "Available",
      wercsStatus: "Registered",
      wercsActionRequired: "—",
    },
    {
      partnerSku: "000010",
      barcode: "0194251000010",
      brand: "Summit Trail",
      productTitle: "Summit Trail Insulated Jacket",
      productDescription: "Packable insulated jacket for cold weather.",
      partnerItemCategory: "Apparel",
      partnerItemSubcategory: "Outerwear",
      shipSpeed: "3 days",
      retailPrice: "$149.99",
      primaryImageUrl: "https://cdn.example.com/summit/insulated-jacket.jpg",
      bu: "Apparel and Accessories",
      division: "Men's Apparel",
      department: "Outerwear",
      itemType: "Jacket",
      protectedBrand: false,
      barcodeStatus: "Available",
      wercsStatus: "UPC is not currently registered",
      wercsActionRequired: "Reach out to Supplier to ensure registration",
    },
  ],
};
