import type { Seller } from "./seller.types";

/** Rich demo sellers with full profile drawer data — kept separate from bulk lead pool */
export const HERO_SELLERS: Seller[] = [
  {
    id: "seller-001",
    legalBusinessName: "Green Co",
    category: "Lighting",
    categories: ["Lighting", "Outdoor Living & Garden"],
    gmv: 1500000,
    skus: 2050,
    viralTrendy: true,
    rating: 4.3,
    marketplaces: ["Amazon", "Walmart"],
    confidenceScore: 9.1,
    location: "Austin, TX",
    businessType: "Manufacturer",
    founded: 2015,
    website: "www.greenco.com",
    description:
      "Green Co specializes in sustainable LED lighting solutions for indoor and outdoor applications. Known for energy-efficient smart lighting products with strong seasonal demand.",
    amazonSkus: 1200,
    amazonRating: 4.4,
    walmartPresent: true,
    socialFollowers: 45000,
    t52wSales: 3200000,
    status: "shortlisted",
  },
  {
    id: "seller-002",
    legalBusinessName: "Harbour",
    category: "Lighting",
    categories: ["Lighting"],
    gmv: 1500000,
    skus: 2050,
    viralTrendy: true,
    rating: 4.3,
    marketplaces: ["Amazon", "Walmart"],
    confidenceScore: 8.4,
    location: "Seattle, WA",
    businessType: "Brand",
    founded: 2012,
    website: "www.harbourlight.com",
    description:
      "Harbour offers premium decorative and functional lighting with a focus on coastal and modern home aesthetics.",
    amazonSkus: 890,
    amazonRating: 4.2,
    walmartPresent: true,
    socialFollowers: 32000,
    t52wSales: 2800000,
    status: "discovered",
  },
  {
    id: "seller-003",
    legalBusinessName: "Thunder Brewing",
    category: "Holiday & Festive Decor",
    categories: ["Holiday & Festive Decor", "Party Supplies"],
    gmv: 1500000,
    skus: 2050,
    viralTrendy: true,
    rating: 4.3,
    marketplaces: ["Amazon", "Walmart"],
    confidenceScore: 7.4,
    location: "Chicago, IL",
    businessType: "Brand",
    founded: 2018,
    website: "www.thunderbrewing.com",
    description:
      "Thunder Brewing creates festive and seasonal decor products with strong holiday catalog depth.",
    amazonSkus: 540,
    amazonRating: 4.1,
    walmartPresent: false,
    socialFollowers: 18000,
    t52wSales: 1100000,
    status: "discovered",
  },
  {
    id: "seller-004",
    legalBusinessName: "Pinnacle Goods",
    category: "Kitchen & Dining",
    categories: ["Kitchen & Dining", "Storage & Organization"],
    gmv: 1500000,
    skus: 2050,
    viralTrendy: true,
    rating: 4.3,
    marketplaces: ["Amazon", "Walmart"],
    confidenceScore: 9.2,
    location: "Boston, MA",
    businessType: "Manufacturer",
    founded: 2010,
    website: "www.pinnaclegoods.com",
    description:
      "Pinnacle Goods is a lifestyle retailer offering a diverse range of branded products including desk clocks, notebooks, phone stands, lamps, and home organization essentials.",
    amazonSkus: 1022,
    amazonRating: 4.4,
    walmartPresent: true,
    socialFollowers: 67000,
    t52wSales: 3900000,
    status: "onboarding",
  },
  {
    id: "seller-005",
    legalBusinessName: "Elevate Labs",
    category: "Lighting",
    categories: ["Lighting", "Holiday & Festive Decor"],
    gmv: 1500000,
    skus: 2050,
    viralTrendy: true,
    rating: 4.3,
    marketplaces: ["Amazon", "Walmart"],
    confidenceScore: 9.1,
    location: "San Francisco, CA",
    businessType: "Brand",
    founded: 2016,
    website: "www.elevatelabs.com",
    description:
      "Elevate Labs creates smart home lighting and decorative lighting products with a tech-forward approach and strong TikTok viral presence.",
    amazonSkus: 780,
    amazonRating: 4.5,
    walmartPresent: false,
    socialFollowers: 120000,
    t52wSales: 4200000,
    status: "shortlisted",
  },
  {
    id: "seller-006",
    legalBusinessName: "Northpoint",
    category: "Kitchen & Dining",
    categories: ["Kitchen & Dining", "Outdoor Living & Garden"],
    gmv: 1500000,
    skus: 2050,
    viralTrendy: true,
    rating: 4.3,
    marketplaces: ["Amazon", "Walmart"],
    confidenceScore: 8.3,
    location: "Denver, CO",
    businessType: "Distributor",
    founded: 2009,
    website: "www.northpointretail.com",
    description:
      "Northpoint is an established distributor covering kitchen, dining, and outdoor living with broad SKU depth and strong operational readiness.",
    amazonSkus: 2100,
    amazonRating: 4.0,
    walmartPresent: true,
    socialFollowers: 21000,
    t52wSales: 5100000,
    status: "discovered",
  },
  {
    id: "seller-007",
    legalBusinessName: "Nexus Retail",
    category: "Holiday & Festive Decor",
    categories: ["Holiday & Festive Decor", "Party Supplies"],
    gmv: 1500000,
    skus: 2050,
    viralTrendy: true,
    rating: 4.3,
    marketplaces: ["Amazon", "Walmart"],
    confidenceScore: 6.4,
    location: "Miami, FL",
    businessType: "Brand",
    founded: 2019,
    website: "www.nexusretail.com",
    description:
      "Nexus Retail focuses on holiday and party supplies with trending seasonal collections.",
    amazonSkus: 320,
    amazonRating: 3.9,
    walmartPresent: false,
    socialFollowers: 9000,
    t52wSales: 680000,
    status: "discovered",
  },
  {
    id: "seller-008",
    legalBusinessName: "Luminate",
    category: "Lighting",
    categories: ["Lighting"],
    gmv: 1500000,
    skus: 2050,
    viralTrendy: true,
    rating: 4.3,
    marketplaces: ["Amazon", "Walmart"],
    confidenceScore: 6.5,
    location: "Portland, OR",
    businessType: "Manufacturer",
    founded: 2017,
    website: "www.luminatelight.com",
    description:
      "Luminate produces architectural and ambient lighting fixtures with a focus on eco-friendly materials.",
    amazonSkus: 420,
    amazonRating: 4.1,
    walmartPresent: false,
    socialFollowers: 14000,
    t52wSales: 920000,
    status: "discovered",
  },
  {
    id: "seller-009",
    legalBusinessName: "Wonder Lights",
    category: "Lighting",
    categories: ["Lighting", "Holiday & Festive Decor"],
    gmv: 1500000,
    skus: 2050,
    viralTrendy: true,
    rating: 4.3,
    marketplaces: ["Amazon", "Walmart"],
    confidenceScore: 9.3,
    location: "Nashville, TN",
    businessType: "Brand",
    founded: 2014,
    website: "www.wonderlights.com",
    description:
      "Wonder Lights is known for string lights, fairy lights, and seasonal lighting with massive social media traction and consistent holiday bestseller status.",
    amazonSkus: 650,
    amazonRating: 4.6,
    walmartPresent: true,
    socialFollowers: 210000,
    t52wSales: 6800000,
    status: "shortlisted",
  },
  {
    id: "seller-010",
    legalBusinessName: "Horizon",
    category: "Lighting",
    categories: ["Lighting", "Outdoor Living & Garden"],
    gmv: 1500000,
    skus: 2050,
    viralTrendy: true,
    rating: 4.3,
    marketplaces: ["Amazon", "Walmart"],
    confidenceScore: 8.5,
    location: "Phoenix, AZ",
    businessType: "Manufacturer",
    founded: 2011,
    website: "www.horizonlighting.com",
    description:
      "Horizon specializes in outdoor and solar-powered lighting with strong Southwest market presence.",
    amazonSkus: 980,
    amazonRating: 4.3,
    walmartPresent: true,
    socialFollowers: 38000,
    t52wSales: 3400000,
    status: "discovered",
  },
  {
    id: "seller-011",
    legalBusinessName: "Greenyard",
    category: "Holiday & Festive Decor",
    categories: ["Holiday & Festive Decor", "Outdoor Living & Garden"],
    gmv: 1500000,
    skus: 2050,
    viralTrendy: true,
    rating: 4.3,
    marketplaces: ["Amazon", "Walmart"],
    confidenceScore: 8.4,
    location: "Atlanta, GA",
    businessType: "Brand",
    founded: 2013,
    website: "www.greenyard.com",
    description:
      "Greenyard focuses on garden decor and outdoor festive displays with strong seasonal catalog and sustainability credentials.",
    amazonSkus: 710,
    amazonRating: 4.2,
    walmartPresent: true,
    socialFollowers: 29000,
    t52wSales: 2600000,
    status: "discovered",
  },
  {
    id: "seller-012",
    legalBusinessName: "Orange Inc",
    category: "Storage & Organization",
    categories: ["Storage & Organization", "Kitchen & Dining"],
    gmv: 127450,
    skus: 256,
    viralTrendy: false,
    rating: 4.1,
    marketplaces: ["Amazon"],
    confidenceScore: 9.3,
    location: "Encino, CA",
    businessType: "Manufacturer",
    founded: 2010,
    website: "www.orangeinc.com",
    description:
      "Orange Inc shows a healthy Amazon footprint with ~$3.9M T52W sales, strong reviews/ratings, and seasonal strength, supported by a clean legal/PR record and meaningful social audiences.",
    amazonSkus: 1022,
    amazonRating: 4.4,
    walmartPresent: false,
    socialFollowers: 55000,
    t52wSales: 3900000,
    status: "onboarding",
  },
  {
    id: "seller-013",
    legalBusinessName: "Mosaic Home",
    category: "Furniture",
    categories: ["Furniture", "Outdoor Living & Garden"],
    gmv: 2200000,
    skus: 340,
    viralTrendy: false,
    rating: 4.5,
    marketplaces: ["Amazon", "Wayfair"],
    confidenceScore: 8.8,
    location: "Los Angeles, CA",
    businessType: "Manufacturer",
    founded: 2008,
    website: "www.mosaichome.com",
    description:
      "Mosaic Home produces premium furniture and outdoor living products with a strong Wayfair track record and expanding Amazon presence.",
    amazonSkus: 180,
    amazonRating: 4.5,
    walmartPresent: false,
    socialFollowers: 82000,
    t52wSales: 4700000,
    status: "discovered",
  },
  {
    id: "seller-014",
    legalBusinessName: "CrispKitchen Co",
    category: "Kitchen & Dining",
    categories: ["Kitchen & Dining"],
    gmv: 980000,
    skus: 520,
    viralTrendy: true,
    rating: 4.4,
    marketplaces: ["Amazon", "Walmart", "Etsy"],
    confidenceScore: 8.1,
    location: "New York, NY",
    businessType: "Brand",
    founded: 2020,
    website: "www.crispkitchen.co",
    description:
      "CrispKitchen Co is a viral DTC kitchen brand known for aesthetic serveware and drinkware. Strong TikTok presence driving rapid growth.",
    amazonSkus: 95,
    amazonRating: 4.6,
    walmartPresent: true,
    socialFollowers: 340000,
    t52wSales: 1800000,
    status: "shortlisted",
  },
  {
    id: "seller-015",
    legalBusinessName: "Rugged & Roam",
    category: "Outdoor Living & Garden",
    categories: ["Outdoor Living & Garden", "Furniture"],
    gmv: 3100000,
    skus: 890,
    viralTrendy: false,
    rating: 4.2,
    marketplaces: ["Amazon", "Walmart", "Home Depot"],
    confidenceScore: 7.9,
    location: "Salt Lake City, UT",
    businessType: "Manufacturer",
    founded: 2007,
    website: "www.ruggedandroam.com",
    description:
      "Rugged & Roam manufactures durable outdoor furniture and garden accessories with strong Home Depot partnership and national distribution.",
    amazonSkus: 620,
    amazonRating: 4.1,
    walmartPresent: true,
    socialFollowers: 42000,
    t52wSales: 7200000,
    status: "discovered",
  },
];
